apiVersion: v1
kind: Namespace
metadata:
  name: sentryflow
  labels:
    istio-injection: disabled # avoid Istio sidecar-injection
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: sentryflow
  name: sentryflow-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sentryflow-cr
rules:
- apiGroups: ["*"]
  verbs: ["*"]
  resources: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sentryflow-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sentryflow-cr
subjects:
- kind: ServiceAccount
  namespace: sentryflow
  name: sentryflow-sa
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: sentryflow
  name: sentryflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sentryflow
  template:
    metadata:
      labels:
        app: sentryflow
    spec:
      serviceAccountName: sentryflow-sa
      containers:
      - name: sentryflow
        image: boanlab/sentryflow:v0.1
        imagePullPolicy: Never  # Use Local Image
        ports:
        - name: otel-grpc
          protocol: TCP
          containerPort: 4317
        - name: wasm-api
          protocol: TCP
          containerPort: 9090
        - name: sentryflow-grpc
          protocol: TCP
          containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  namespace: sentryflow
  name: sentryflow
spec:
  selector:
    app: sentryflow
  ports:
  - name: otel-grpc
    protocol: TCP
    port: 4317
    targetPort: 4317
  - name: wasm-api
    protocol: TCP
    port: 9090
    targetPort: 9090
  - name: sentryflow-grpc
    protocol: TCP
    port: 8080
    targetPort: 8080